### ISSUE TITLE
Funcionalidade para o estudante poder solicitar certificado dos Programas da Coordenadoria dos Programas Acadêmicos a PREG

### ISSUE THREAD

**Issue by douglasfsbatista** [lmtsufape/Certifica#477]

**Comment by douglasfsbatista** [comment]
Campos necessários para cada programa:


CERTIFICADO DO PROGRAMA DE MONITORIA

- Nome do discente
- Curso
- Disciplina
- Semestre letivo da monitoria
- Carga horária
- Orientador



CERTIFICADO DO PROGRAMA DE TUTORIA

- Nome do discente
- Curso
- Área
- Semestre letivo da tutoria
- Carga horária
- Orientador



CERTIFICADO DO PROGRAMA DE ATIVIDADES DE VIVÊNCIA INTERDISCIPLINAR – PAVI
Nome do discente

- Curso
- Semestre letivo
- Área
- Local de realização das atividades
- Período de realização das atividades
- Carga horária
- Orientador



CERTIFICADO DO PROGRAMA DE BOLSAS DE INCENTIVO ACADÊMICO – BIA

- Nome do discente
- Curso
- Projeto
- Período de realização
- Carga horária
- Orientador(s)

**Comment by magnosillas** [comment]
adicionar arquivo de relatorio
