### ISSUE TITLE
Criação de perfil intermediário de colaborador para funções básicas;

### ISSUE THREAD

**Issue by Dev-LucasMelo** [lmtsufape/Certifica#505]
- Perfil terá funções como a de gestor (rever o que pode ou não pode) 
- Objetivo : Diminuir a carga de trabalho para gestores em geral e dividir tarefas com esse novo perfil

**Comment by magnosillas** [comment]
nao pode emitir acoes, n pode ver usuarios, n pode alterar (aprovar/reprovar) solicitacoes
