### ISSUE TITLE
Verificar o envio de e-mails pelo Certifica ao gestor receber solicitações para avaliação

### ISSUE THREAD

**Issue by lmts-ufape** [lmtsufape/Certifica#582]

**Comment by Rener1** [comment]
O problema consiste nessa linha de código: `$user = $acao->unidadeAdministrativa->users->where('perfil_id', 3)->first();` no AcaoController, onde ele pega o primeiro gestor que está associado a unidade administrativa em que a ação foi submetida. Porém, nesse caso específico, gestor escolhido não corresponde com o esperado e o E-mail é enviado para um destinatário que não existe.

A solução envolve remover a conta de usuário na qual o E-mail está sendo enviado ou modificar o código para que envie para todos e não apenas para o primeiro encontrado.
